### ISSUE TITLE
Não funciona com a versão 4.2.0-RC3 do vraptor

### ISSUE THREAD

**Issue by albertopida** [caelum/vraptor-i18n#48]
Caros

Estou tentando usar esse plugin em meu projeto, que esta configurado com o vraptor 4.2.0-RC3.
Porém nessa versão do vraptor tiveram algumas alterações nos construtores que fizeram com que o plugin deixasse de funcionar.

Tentei corrigir para mandar um pull request, o teste I18nLinkToHandlerTest esta quebrando direto. E não consigo entender a lógica desse teste..

**Comment by gpassero** [comment]
Aqui está dando erro também, versão 4.2.0-RC3 também:
´´´
Caused by: java.lang.NoSuchMethodError: br.com.caelum.vraptor.http.route.PathAnnotationRoutesParser.<init>(Lbr/com/caelum/vraptor/http/route/Router;)V
	at br.com.caelum.vraptor.i18n.routes.I18nRoutesParser.<init>(I18nRoutesParser.java:39)
	at br.com.caelum.vraptor.i18n.routes.I18nRoutesParser.<init>(I18nRoutesParser.java:34)
	at br.com.caelum.vraptor.i18n.routes.I18nRoutesParser$Proxy$_$$_WeldClientProxy.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
´´´

**Comment by gpassero** [comment]
Alberto,
Acabei de liberar um jar com a correção. 
Ainda não fiz todos os testes, agradeço se puder ajudar.
https://github.com/gpassero/vraptor-i18n/blob/master/releases/vraptor-i18n-4.2.0-RC3-beta.jar

**Comment by gpassero** [comment]
Liberei uma correção para esse problema. Agradeço se puder ajudar a testar. 
Mais informações em: https://github.com/gpassero/vraptor-i18n

**Comment by albertopida** [comment]
@gpassero eu tinha feito um clone do projeto e alterado também. mas não consegui resolver o erro no teste I18nRoutesResourceTest. 
Fiz o clone do seu projeto e ele também esta quebrando.. 
Chegaste a ver isso?

**Comment by gpassero** [comment]
@albertopida  Aqui tive que corrigir outra classe de teste para usar ReflectionProvider, mas essa não deu problema.Todos os testes estão OK aqui.
Esse teste depende do arquivo /src/test/resources/routes_pt_BR.properties. Verifica se ele existe aí. Você tem uma cópia exata do meu fork ou mudou algo?
Em últimos casos vais precisar debugar o teste dessa classe para descobrir o que está acontecendo. Manda o erro aí!

**Comment by albertopida** [comment]
@gpassero fiz o fork do seu projeto, não alterei nada e gerei o jar. 
Porém não esta dando certo, não acontece nada.
Criei o arquivo messages.properties dentro de src/main/resources, 
coloquei uma chave e na jsp e não aconteceu nada..

**Comment by gpassero** [comment]
Para confirmar que você importou o jar, faz um Inject do Translator no seu
controller. Se der erro de dependência tem que verificar a importação do
jar. (Eu passei por um problema assim)
Em 13/01/2016 13:12, "albertopida" <notifications@github.com> escreveu:

**Comment by gpassero** [comment]
Você tentou importar o projeto automaticamente conforme orientações na
minha página? Se fizer aquilo não precisar importar o jar manualmente.
Em 13/01/2016 13:15, "Guilherme Passero" <guilherme.passer@gmail.com>
escreveu:

**Comment by albertopida** [comment]
Foi falta de atenção minha, agora segui as orientações do seu projeto e deu certo.
Vou testar mais um pouco. 
Mas creio que o problema foi a alteração nos construtores do vraptor que quebrou a compatibilidade.
Faz um pullrequest para o projeto..

**Comment by gpassero** [comment]
Sim, não tive que alterar nenhuma funcionalidade, só adicionar uns
parâmetros. Farei o request.

Em 13 de janeiro de 2016 16:17, albertopida <notifications@github.com>
escreveu:

> Foi falta de atenção minha, agora segui as orientações do seu projeto e
> deu certo.
> Vou testar mais um pouco.
> Mas creio que o problema foi a alteração nos construtores do vraptor que
> quebrou a compatibilidade.
> Faz um pullrequest para o projeto..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caelum/vraptor-i18n/issues/48#issuecomment-171386162>.
>



-- 

Att,
Guilherme Passero.

**Comment by gpassero** [comment]
https://github.com/caelum/vraptor-i18n/pull/49

**Comment by albertopida** [comment]
Nada ainda? ;s

**Comment by Turini** [comment]
@albertopida @gpassero acabei de fazer o release, em algumas horas estará disponível no repositório do maven.
